
name: publish

on:
  release:
    types:
      - created

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python "3.13"
      uses: actions/setup-python@v2
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov build
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      run: |
        pip install .
    - name: Run Test
      run: |
         pytest tests --doctest-modules
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      if:  github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
